Update automate-validate-qa.yml

diff --git a/.github/workflows/automate-validate-qa.yml b/.github/workflows/automate-validate-qa.yml
--- a/.github/workflows/automate-validate-qa.yml
+++ b/.github/workflows/automate-validate-qa.yml
@@ -11,17 +11,25 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
         with:
-         fetch-depth: 0
+          fetch-depth: 0
+
+      - name: Cache node modules
+        id: cache-node-modules
+        uses: actions/cache@v2
+        with:
+          path: ~/.npm
+          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-modules-
 
       - name: Setup Node
+        if: steps.cache-node-modules.outputs.cache-hit != 'true'
         uses: actions/setup-node@v2
         with:
-          path: |
-            **/node_modules
-          # Adding node version as cache key
-          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}
-            
+          node-version: "16.x"
+                
       - name: Install Dependencies
+        if: steps.cache-node-modules.outputs.cache-hit != 'true'
         run: |
           npm install sfdx-cli --global
           echo y | sfdx plugins:install sfdx-git-delta
@@ -30,12 +38,12 @@ jobs:
       - name: 'Populate auth file with QA_AUTH_URL secret'
         shell: bash
         run: |
-            echo ${{ secrets.QA_AUTH_URL}} > ./QA_AUTH_URL.txt
-            secretFileSize=$(wc -c "./QA_AUTH_URL.txt" | awk '{print $1}')
-            if [ $secretFileSize == 1 ]; then
-                echo "Missing QA_AUTH_URL secret. Is this workflow running on a fork?";
-                exit 1;
-            fi
+          echo ${{ secrets.QA_AUTH_URL }} > ./QA_AUTH_URL.txt
+          secretFileSize=$(wc -c "./QA_AUTH_URL.txt" | awk '{print $1}')
+          if [ $secretFileSize == 1 ]; then
+            echo "Missing QA_AUTH_URL secret. Is this workflow running on a fork?";
+            exit 1;
+          fi
       
       - name: Authenticate with QA 
         run: |
@@ -55,4 +63,3 @@ jobs:
               --postdestructivechanges destructiveChanges/destructiveChanges.xml \
               --testlevel=RunLocalTests \
               -u devhub \
-
