Update automate-validate-qa.yml

diff --git a/.github/workflows/automate-validate-qa.yml b/.github/workflows/automate-validate-qa.yml
--- a/.github/workflows/automate-validate-qa.yml
+++ b/.github/workflows/automate-validate-qa.yml
@@ -11,24 +11,17 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
         with:
-          fetch-depth: 0
+         fetch-depth: 0
 
       - name: Setup Node
         uses: actions/setup-node@v2
         with:
-          node-version: "16.x"
-          
-      - name: Cache node modules
-        id: cache-node-modules
-        uses: actions/cache@v2
-        with:
-          path: ~/.npm
-          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-node-modules-
+          path: |
+            **/node_modules
+          # Adding node version as cache key
+          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}
             
       - name: Install Dependencies
-        if: steps.cache-node-modules.outputs.cache-hit != 'true'
         run: |
           npm install sfdx-cli --global
           echo y | sfdx plugins:install sfdx-git-delta
@@ -37,12 +30,12 @@ jobs:
       - name: 'Populate auth file with QA_AUTH_URL secret'
         shell: bash
         run: |
-          echo ${{ secrets.QA_AUTH_URL }} > ./QA_AUTH_URL.txt
-          secretFileSize=$(wc -c "./QA_AUTH_URL.txt" | awk '{print $1}')
-          if [ $secretFileSize == 1 ]; then
-            echo "Missing QA_AUTH_URL secret. Is this workflow running on a fork?";
-            exit 1;
-          fi
+            echo ${{ secrets.QA_AUTH_URL}} > ./QA_AUTH_URL.txt
+            secretFileSize=$(wc -c "./QA_AUTH_URL.txt" | awk '{print $1}')
+            if [ $secretFileSize == 1 ]; then
+                echo "Missing QA_AUTH_URL secret. Is this workflow running on a fork?";
+                exit 1;
+            fi
       
       - name: Authenticate with QA 
         run: |
@@ -63,8 +56,3 @@ jobs:
               --testlevel=RunLocalTests \
               -u devhub \
 
-      - name: Restore node_modules from cache
-        if: steps.cache-node-modules.outputs.cache-hit == 'true'
-        run: |
-          mkdir -p ~/.npm
-          mv ${{ runner.workspace }}/.npm/* ~/.npm
