Update cachedemo.yml

diff --git a/.github/workflows/cachedemo.yml b/.github/workflows/cachedemo.yml
--- a/.github/workflows/cachedemo.yml
+++ b/.github/workflows/cachedemo.yml
@@ -36,3 +36,32 @@ jobs:
           npm install sfdx-cli --global
           echo y | sfdx plugins:install sfdx-git-delta
           sfdx plugins
+
+      - name: 'Populate auth file with QA_AUTH_URL secret'
+        shell: bash
+        run: |
+            echo ${{ secrets.QA_AUTH_URL}} > ./QA_AUTH_URL.txt
+            secretFileSize=$(wc -c "./QA_AUTH_URL.txt" | awk '{print $1}')
+            if [ $secretFileSize == 1 ]; then
+                echo "Missing QA_AUTH_URL secret. Is this workflow running on a fork?";
+                exit 1;
+            fi
+      
+      - name: Authenticate with QA 
+        run: |
+          sfdx force:auth:sfdxurl:store -f ./QA_AUTH_URL.txt -d -a devhub
+            
+      - name: 'Create delta packages for new, modified or deleted metadata'
+        run: |
+          sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output .
+
+      - name: Print package.xml
+        run: cat package/package.xml
+      
+      - name: Validate with QA
+        run: |
+          sfdx force:source:deploy --checkonly \
+              --manifest=package/package.xml \
+              --postdestructivechanges destructiveChanges/destructiveChanges.xml \
+              --testlevel=RunLocalTests \
+              -u devhub \
